### ISSUE TITLE
Is the extension versioned

### ISSUE THREAD

**Issue by Praveengostu** [rixrix/vscode-terraform-snippets#29]
Is the extension versioned. So will i be able to get older achives of the extension. Say this version has support for some and next version has support for more and i need to access old version

**Comment by rixrix** [comment]
hello @Praveengostu unfortunately no, the first few releases were chucked into 1 big `json` file, though as you mentioned we might be able to do that in the next releases. I'm happy and open for any ideas on how we can better manage the versioning. thank you

**Comment by rixrix** [comment]
@Praveengostu closing this off. Suggestions are always welcome. closing this off. thanks

**Comment by rixrix** [comment]
@Praveengostu thank you for asking this, apparently looking back at my commit logs I realised I was following the `conventional-changelog` convention, particularly the angular preset. I've regenerated all the CHANGELOG.md contents as well as the Github releases - so in saying that you should be able to pull older history, though not much really. 

let me know. thanks

**Comment by Praveengostu** [comment]
@rixrix Thankyou for the response. Apart from that I was also intrested in if the plugin/extension versioned. So vs code will allow me to install a older version of the the extension

**Comment by rixrix** [comment]
> @Praveengostu  re: older version

at the moment there's no official way based on from this ticket, https://github.com/Microsoft/vscode/issues/12764 there's a hack mentioned in the ticket - haven't tried it though. 

However, if you want to do that for the sake of debugging - you can do some symlinking trick, it was also asked here before see #30 

thanks
