### ISSUE TITLE
test terraform snippet locally

### ISSUE THREAD

**Issue by maestrofx** [rixrix/vscode-terraform-snippets#30]
Hi @rixrix ,

A tricky question, I've added Rancher provider, is there any ways I can test it locally without repeatedly publish it to vscode marketplace or waiting for PR to this repo?

Thank you.

**Comment by rixrix** [comment]
hello @maestrofx 

what I'm doing is a little bit hacky-ish - seems to work though. I symlinked the terraform snippets folder inside the VScode's extension folder.

Here's a quick info of the location of vscode extension per platform
https://code.visualstudio.com/docs/editor/extension-gallery#_common-questions

here's my local setup on Win10

![terraform-testing](https://user-images.githubusercontent.com/36795/30404262-fa3c828a-9939-11e7-96d7-fe338c60d43e.png)

I'm happy to test your Rancher changes. I'm looking forward to your PR, thanks

**Comment by maestrofx** [comment]
Thanks @rixrix , I'll check and submit PR(s) asap.

**Comment by rixrix** [comment]
thanks. closing this off
